# Generated by Django 4.2.14 on 2024-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='file')),
            ],
        ),
    ]
