# Generated by Django 4.2.14 on 2024-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pav', '0004_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='adresse',
            field=models.CharField(default=True, max_length=300, null=True),
        ),
    ]
